// SPDX-License-Identifier: GPL-3.0-or-later
// The Moment — derived from FilaBridge (https://github.com/needo37/filabridge)
// Copyright (C) 2025 needo37 / Copyright (C) 2026 maudy2u

package main

// =============================================================================
// the-moment_test.go
// =============================================================================
// Unit tests for the state machine and filament usage parsing.
//
// Run with:
//   go test ./... -v
//   go test ./... -v -run TestParseGcodeFilamentUsage
// =============================================================================

import (
	"fmt"
	"math"
	"os"
	"strings"
	"testing"
)

// =============================================================================
// ParseGcodeFilamentUsage Tests
// =============================================================================

// TestParseGcodeFilamentUsage_SingleToolhead tests single-toolhead .gcode (PrusaSlicer comment)
func TestParseGcodeFilamentUsage_SingleToolhead(t *testing.T) {
	client := &PrusaLinkClient{}

	gcode := `; generated by PrusaSlicer 2.8.0
; filament used [g] = 12.45
G28 ; home all axes`

	usage, err := client.ParseGcodeFilamentUsage([]byte(gcode))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(usage) != 1 {
		t.Fatalf("expected 1 toolhead, got %d", len(usage))
	}

	assertApprox(t, "toolhead 0 grams", 12.45, usage[0].Grams, 0.01)
	assertApprox(t, "toolhead 0 mm", 0, usage[0].MM, 0.001) // no [mm] in source
}

// TestParseGcodeFilamentUsage_MultiToolhead_INDX8 tests an 8-toolhead INDX scenario
func TestParseGcodeFilamentUsage_MultiToolhead_INDX8(t *testing.T) {
	client := &PrusaLinkClient{}

	// Simulate 8 toolheads — toolheads 2, 5 unused (0g)
	gcode := `; filament used [g] = 45.10, 30.20, 0.00, 12.50, 8.75, 0.00, 22.30, 5.60`

	usage, err := client.ParseGcodeFilamentUsage([]byte(gcode))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Only non-zero entries should be in the map
	if len(usage) != 6 {
		t.Fatalf("expected 6 active toolheads, got %d: %v", len(usage), usage)
	}

	assertApprox(t, "toolhead 0", 45.10, usage[0].Grams, 0.01)
	assertApprox(t, "toolhead 1", 30.20, usage[1].Grams, 0.01)
	assertApprox(t, "toolhead 3", 12.50, usage[3].Grams, 0.01)
	assertApprox(t, "toolhead 4", 8.75, usage[4].Grams, 0.01)
	assertApprox(t, "toolhead 6", 22.30, usage[6].Grams, 0.01)
	assertApprox(t, "toolhead 7", 5.60, usage[7].Grams, 0.01)

	// Zero-weight toolheads must NOT be in the map
	if _, ok := usage[2]; ok {
		t.Error("toolhead 2 has 0g but appeared in usage map")
	}
	if _, ok := usage[5]; ok {
		t.Error("toolhead 5 has 0g but appeared in usage map")
	}
}

// TestParseGcodeFilamentUsage_BGcodeFormat tests .bgcode embedded metadata (no semicolon)
func TestParseGcodeFilamentUsage_BGcodeFormat(t *testing.T) {
	client := &PrusaLinkClient{}

	bgcode := `filament used [g]=18.92,7.34`

	usage, err := client.ParseGcodeFilamentUsage([]byte(bgcode))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(usage) != 2 {
		t.Fatalf("expected 2 entries, got %d", len(usage))
	}
	assertApprox(t, "toolhead 0", 18.92, usage[0].Grams, 0.01)
	assertApprox(t, "toolhead 1", 7.34, usage[1].Grams, 0.01)
}

// TestParseGcodeFilamentUsage_MMFallback tests the [mm] → grams fallback when [g] is absent
func TestParseGcodeFilamentUsage_MMFallback(t *testing.T) {
	client := &PrusaLinkClient{}

	// 1000mm of 1.75mm PLA → roughly 2.97g
	gcode := `; filament used [mm] = 1000.00`

	usage, err := client.ParseGcodeFilamentUsage([]byte(gcode))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(usage) != 1 {
		t.Fatalf("expected 1 entry, got %d", len(usage))
	}

	// Check within 10% of expected grams value
	expectedG := math.Pi * (1.75 / 2) * (1.75 / 2) * 1000.0 / 1000.0 * 1.24
	assertApprox(t, "toolhead 0 grams (mm fallback)", expectedG, usage[0].Grams, expectedG*0.10)
	assertApprox(t, "toolhead 0 mm", 1000.0, usage[0].MM, 0.01)
}

// TestParseGcodeFilamentUsage_BothGAndMM tests the typical PrusaSlicer case where both
// [g] and [mm] comments are present — mm must be captured alongside grams.
func TestParseGcodeFilamentUsage_BothGAndMM(t *testing.T) {
	client := &PrusaLinkClient{}

	gcode := `; generated by PrusaSlicer 2.8.0
; filament used [mm] = 4234.56, 1876.30
; filament used [cm3] = 10.10, 4.48
; filament used [g] = 12.52, 5.55
; filament used [cost] = 0.10, 0.04`

	usage, err := client.ParseGcodeFilamentUsage([]byte(gcode))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(usage) != 2 {
		t.Fatalf("expected 2 entries, got %d: %v", len(usage), usage)
	}

	assertApprox(t, "T0 grams", 12.52, usage[0].Grams, 0.01)
	assertApprox(t, "T0 mm", 4234.56, usage[0].MM, 0.01)
	assertApprox(t, "T1 grams", 5.55, usage[1].Grams, 0.01)
	assertApprox(t, "T1 mm", 1876.30, usage[1].MM, 0.01)
}

// TestParseGcodeFilamentUsage_Empty tests a G-code file with no filament metadata
func TestParseGcodeFilamentUsage_Empty(t *testing.T) {
	client := &PrusaLinkClient{}

	gcode := `G28
G1 X100 Y100 Z10
; no filament metadata here`

	usage, err := client.ParseGcodeFilamentUsage([]byte(gcode))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(usage) != 0 {
		t.Errorf("expected empty usage map, got %v", usage)
	}
}

// =============================================================================
// State Machine / Constants Tests
// =============================================================================

// TestPrinterStateConstants verifies all required states are defined
func TestPrinterStateConstants(t *testing.T) {
	states := []string{
		StateIdle,
		StatePrinting,
		StateFinished,
		StatePaused,
		StateStopped,
		StateAttention,
		StateOffline,
		StateNotConfigured,
	}

	for _, s := range states {
		if s == "" {
			t.Errorf("a state constant is empty string — check constants.go")
		}
	}

	// Verify against actual PrusaLink API values (case-sensitive)
	assertEqual(t, "StateIdle", "IDLE", StateIdle)
	assertEqual(t, "StatePrinting", "PRINTING", StatePrinting)
	assertEqual(t, "StateFinished", "FINISHED", StateFinished)
	assertEqual(t, "StatePaused", "PAUSED", StatePaused)
	assertEqual(t, "StateStopped", "STOPPED", StateStopped)
	assertEqual(t, "StateAttention", "ATTENTION", StateAttention)
}

// TestMaxToolheads verifies MaxToolheads covers INDX 8-head
func TestMaxToolheads(t *testing.T) {
	const indxHeadCount = 8
	if MaxToolheads < indxHeadCount {
		t.Errorf("MaxToolheads=%d is less than INDX head count=%d", MaxToolheads, indxHeadCount)
	}
}

// =============================================================================
// Partial Usage (Cancelled Print) Tests
// =============================================================================

// TestCancelledPrintScaling verifies partial filament calculation
func TestCancelledPrintScaling(t *testing.T) {
	fullUsage := map[int]float64{
		0: 100.0,
		1: 50.0,
	}

	progressPct := 60.0
	safetyMargin := 0.95
	scale := (progressPct / 100.0) * safetyMargin

	partialUsage := make(map[int]float64)
	for toolheadID, weight := range fullUsage {
		partialUsage[toolheadID] = weight * scale
	}

	// At 60% progress with 5% safety margin, expect 57% of full usage
	assertApprox(t, "toolhead 0 partial", 57.0, partialUsage[0], 0.1)
	assertApprox(t, "toolhead 1 partial", 28.5, partialUsage[1], 0.1)
}

// TestCancelledPrintAtZeroProgress verifies no deduction when progress is 0%
func TestCancelledPrintAtZeroProgress(t *testing.T) {
	progressPct := 0.0
	if progressPct <= 0 {
		// This is the guard condition in handlePrusaLinkPrintCancelled
		return // Correct — no deduction
	}
	t.Error("should have returned early for 0% progress")
}

// =============================================================================
// Toolhead Name Tests
// =============================================================================

// TestToolheadNameFormat verifies the location name format
func TestToolheadNameFormat(t *testing.T) {
	printerName := "Core One L"
	toolheadID := 3
	displayName := "T3-Black"

	locationName := fmt.Sprintf("%s - %s", printerName, displayName)
	expected := "Core One L - T3-Black"
	if locationName != expected {
		t.Errorf("expected '%s', got '%s'", expected, locationName)
	}

	// Default name format
	defaultName := fmt.Sprintf("%s - Toolhead %d", printerName, toolheadID)
	if defaultName != "Core One L - Toolhead 3" {
		t.Errorf("unexpected default name: %s", defaultName)
	}
}

// =============================================================================
// Docker-compose Validation (Integration Smoke Test)
// =============================================================================

// TestDockerComposeHasRequiredServices is a structural test that validates
// the docker-compose.yml has the expected service names in it.
// This runs without Docker — it just checks the file content.
func TestDockerComposeHasRequiredServices(t *testing.T) {
	content, err := os.ReadFile("docker-compose.yml")
	if err != nil {
		t.Fatalf("could not read docker-compose.yml: %v", err)
	}

	requiredStrings := []string{
		"spoolman",
		"the-moment",
		"service_healthy",
		"7912",
	}

	for _, s := range requiredStrings {
		if !strings.Contains(string(content), s) {
			t.Errorf("docker-compose.yml missing expected string: '%s'", s)
		}
	}
}

// =============================================================================
// Helpers
// =============================================================================

func assertApprox(t *testing.T, label string, expected, actual, tolerance float64) {
	t.Helper()
	diff := math.Abs(expected - actual)
	if diff > tolerance {
		t.Errorf("%s: expected %.4f ± %.4f, got %.4f (diff %.4f)", label, expected, tolerance, actual, diff)
	}
}

func assertEqual(t *testing.T, label, expected, actual string) {
	t.Helper()
	if expected != actual {
		t.Errorf("%s: expected '%s', got '%s'", label, expected, actual)
	}
}
